networks:
  db_docker-network:
    external: true

services:
  spring:
    container_name: backend
    image: spring:0.1
    build:
      context: .
    ports:
      - 8080:8080
    networks:
      - mimlnetwork
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}