networks:
  mimlnetwork:
    external: true

services:
  backend_webflux:
    container_name: backend_webflux
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - temp_volume:/app/temp
    ports:
      - 8080:8080
    networks:
      - mimlnetwork
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - TEMP_DIR=/app/temp
volumes:
  temp_volume:
