spring:
  application:
    name: reco

  profiles:
    include: auth
    active: prod

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: false

#  mvc:
#    contentnegotiation:
#      favor-parameter: true
#      media-types:
#        mp4: video/mp4
#        mp3: audio/mpeg
#        wav: audio/wav
#        m4a: audio/mp4
#        aac: audio/aac
#        ogg: audio/ogg
#        flac: audio/flac


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        web:
          multipart: DEBUG
#server:
#  tomcat:
#    max-http-form-post-size: 100MB
#    max-swallow-size: 100MB