spring:
  application:
    name: reco

  profiles:
    include: auth
    active: prod


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 100MB
      max-file-size: 2GB
      max-request-size: 2GB
      location: ${TEMP_DIR:/app/temp}

#  mvc:
#    contentnegotiation:
#      favor-parameter: true
#      media-types:
#        mp4: video/mp4
#        mp3: audio/mpeg
#        wav: audio/wav
#        m4a: audio/mp4
#        aac: audio/aac
#        ogg: audio/ogg
#        flac: audio/flac


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace